const viteEnv =
  typeof import.meta !== "undefined" ? import.meta.env : {};

const nodeEnv =
  typeof process !== "undefined" ? process.env : {};

export const ENV = {
  // ===== MODO TEST =====
  TEST_MODE:
    (viteEnv.VITE_TEST_MODE ?? nodeEnv.VITE_TEST_MODE) === "true",

  TEST_USER_EMAIL:
    viteEnv.VITE_TEST_USER_EMAIL ?? nodeEnv.VITE_TEST_USER_EMAIL,

  // ===== AZURE AD =====
  AZURE_CLIENT_ID:
    viteEnv.VITE_REACT_APP_AZURE_CLIENT_ID ??
    nodeEnv.VITE_REACT_APP_AZURE_CLIENT_ID,

  AZURE_TENANT_ID:
    viteEnv.VITE_REACT_APP_AZURE_TENANT_ID ??
    nodeEnv.VITE_REACT_APP_AZURE_TENANT_ID,

  // ===== BFF BASE =====
  BFF_BASE:
    viteEnv.VITE_SERVICE_ENDPOINT_BFF_BASE ??
    nodeEnv.VITE_SERVICE_ENDPOINT_BFF_BASE,

  // ===== CLIENTES =====
  SERVICE_CLIENTES:
    viteEnv.VITE_SERVICE_ENDPOINT_BFF_OBTENER_CLIENTES ??
    nodeEnv.VITE_SERVICE_ENDPOINT_BFF_OBTENER_CLIENTES,

  SERVICE_CLIENTES_REGISTRO:
    viteEnv.VITE_SERVICE_ENDPOINT_BFF_REGISTRO_CLIENTES ??
    nodeEnv.VITE_SERVICE_ENDPOINT_BFF_REGISTRO_CLIENTES,

  SERVICE_ROLES:
    viteEnv.VITE_SERVICE_ENDPOINT_BFF_ROLES ??
    nodeEnv.VITE_SERVICE_ENDPOINT_BFF_ROLES,

  SERVICE_CONTACTO:
    viteEnv.VITE_SERVICE_ENDPOINT_BFF_CONTACTO ??
    nodeEnv.VITE_SERVICE_ENDPOINT_BFF_CONTACTO,

  // ===== PRODUCTOS =====
  SERVICE_PRODUCTOS:
    viteEnv.VITE_SERVICE_ENDPOINT_BFF_PRODUCTOS ??
    nodeEnv.VITE_SERVICE_ENDPOINT_BFF_PRODUCTOS,

  SERVICE_CATEGORIAS:
    viteEnv.VITE_SERVICE_ENDPOINT_BFF_CATEGORIAS ??
    nodeEnv.VITE_SERVICE_ENDPOINT_BFF_CATEGORIAS,

  SERVICE_INVENTARIOS:
    viteEnv.VITE_SERVICE_ENDPOINT_BFF_INVENTARIOS ??
    nodeEnv.VITE_SERVICE_ENDPOINT_BFF_INVENTARIOS,

  // ===== ORDENES =====
  SERVICE_ORDENES:
    viteEnv.VITE_SERVICE_ENDPOINT_BFF_ORDENES ??
    nodeEnv.VITE_SERVICE_ENDPOINT_BFF_ORDENES,

  // ===== OTROS =====
  BUCKET_IMAGES:
    viteEnv.VITE_BUCKET ?? nodeEnv.VITE_BUCKET,

  BFF_METRICS:
    viteEnv.VITE_BFF_METRICS ?? nodeEnv.VITE_BFF_METRICS,
};